# Generated by Django 5.1.4 on 2024-12-21 19:50

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdemo',
            name='demo_file',
            field=models.FileField(help_text='Path to the demo directory in S3', upload_to=products.models.demo_file_path),
        ),
        migrations.AlterField(
            model_name='productdemo',
            name='download_file',
            field=models.FileField(help_text='Path to the downloadable file in S3', upload_to=products.models.download_file_path),
        ),
    ]
