# Generated by Django 5.1.4 on 2024-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdemo_demo_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
