# Generated by Django 5.1.4 on 2024-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_productscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/{instance.product.id}/'),
        ),
    ]
