# Generated by Django 5.1.4 on 2024-12-22 12:09

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(upload_to=products.models.screenshot_path),
        ),
    ]
