# Generated by Django 5.1.4 on 2024-12-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(upload_to='products/screenshots/'),
        ),
    ]
